CREATE TABLE IF NOT EXISTS fight (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  link VARCHAR(80) NOT NULL UNIQUE,
  event_id INTEGER NOT NULL REFERENCES event (id) ON DELETE CASCADE,
  fighter_1_id INTEGER NOT NULL REFERENCES fighter (id) ON DELETE CASCADE,
  fighter_2_id INTEGER NOT NULL REFERENCES fighter (id) ON DELETE CASCADE,
  tried INTEGER NOT NULL DEFAULT 0,
  success INTEGER
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fight_link ON fight (link);
