[defaults]
delay = 2.5

[directories]
data = "/home/woitek/repos/mma_project/ufcstats_scraper/data"
log = "/home/woitek/repos/mma_project/ufcstats_scraper/log"

[logger]
enabled = true
level = "DEBUG"

[requests]
timeout = 7.0
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.3"
