[tool.pyright]
useLibraryCodeForTypes = true
analyzeUnannotatedFunctions = false
reportUnnecessaryCast = "information"
reportUnnecessaryTypeIgnoreComment = "information"

[tool.ruff]
line-length = 110
target-version = "py311"
unsafe-fixes = false

[tool.ruff.lint]
select = [
  "C401",
  "C417",
  "E741",
  "EM",
  "F401",
  "F841",
  "FBT",
  "G004",
  "I",
  "N806",
  "PLR0402",
  "PLR1722",
  "PT018",
  "PTH",
  "PYI036",
  "RET502",
  "RUF100",
  "S113",
  "SIM105",
  "SIM108",
  "TRY201",
  "UP",
]

[tool.ruff.lint.isort]
case-sensitive = true
