[tool.pyright]
useLibraryCodeForTypes = true
analyzeUnannotatedFunctions = false
reportUnnecessaryCast = "information"
reportUnnecessaryTypeIgnoreComment = "information"

[tool.ruff]
line-length = 110
target-version = "py311"
extend-safe-fixes = ["UP"]

[tool.ruff.lint]
select = ["I", "UP"]

[tool.ruff.lint.isort]
case-sensitive = true
