[tool.black]
line-length = 110
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 110
force_single_line = true

[tool.pyright]
stubPath = "/home/woitek/python-type-stubs"
useLibraryCodeForTypes = true
analyzeUnannotatedFunctions = false
reportUnnecessaryCast = "information"
reportUnnecessaryTypeIgnoreComment = "information"
