[tool.pyright]
useLibraryCodeForTypes = true
analyzeUnannotatedFunctions = false
reportUnnecessaryCast = "information"
reportUnnecessaryTypeIgnoreComment = "information"

[tool.ruff]
line-length = 110
target-version = "py311"
unsafe-fixes = true

[tool.ruff.lint]
select = ["F401", "I", "UP"]

[tool.ruff.lint.isort]
case-sensitive = true
