[tool.pyright]
useLibraryCodeForTypes = true
analyzeUnannotatedFunctions = false
reportUnnecessaryCast = "information"
reportUnnecessaryTypeIgnoreComment = "information"

[tool.ruff]
line-length = 110
target-version = "py311"

[tool.ruff.lint]
select = ["I"]

[tool.ruff.lint.isort]
case-sensitive = true
